"""Compile high-level work-packet intent into internal validation contracts.

The orchestrator owns goals and acceptance criteria. This module owns the
executable details consumed by the validator and worker auto-feedback loop.
Those details never need to be generated by the planning model.
"""

from __future__ import annotations

import re
import shlex
import socket
from pathlib import Path
from typing import Any, Optional

from src.tools.paths import get_workspace_root, normalize_workspace_path
from src.sandbox.process_manager import get_allowed_ports

_QUOTED_TEXT = re.compile(r"""['"]([^'"]{2,120})['"]""")

# Structural UI signals. Deliberately NOT prose matching: substring hints
# like "ui" match "build", "require", "guidance" and once compiled a ui_smoke
# contract for a PyTorch training repo because a criterion mentioned
# `build_trainer`. UI-ness is decided from file types, imports, and
# manifests — never from free text.
_UI_SUFFIXES = frozenset({".html", ".htm", ".jsx", ".tsx", ".vue", ".svelte", ".astro"})
_JS_SUFFIXES = frozenset({".js", ".jsx", ".ts", ".tsx"})
_STREAMLIT_IMPORT_RE = re.compile(
    r"^\s*(import streamlit\b|from streamlit(?:\s+import|\s*$))",
    re.MULTILINE,
)
_MAX_PROBE_BYTES = 200_000


def _profile(milestone: dict[str, Any]) -> str:
    value = str(milestone.get("validation_profile", "auto")).strip().lower()
    if value in {"auto", "ui", "python", "lint", "structural"}:
        return value
    return ""


def _is_ui_milestone(milestone: dict[str, Any]) -> bool:
    """Legacy alias — delegates to the structural classifier."""
    profile, _reason = classify_validation_target(milestone)
    return profile == "ui"


def _resolve_target(path: str, workspace: Path) -> Optional[Path]:
    """Resolve a milestone target inside the workspace; None when absent."""
    candidate = (workspace / path).resolve()
    try:
        candidate.relative_to(workspace.resolve())
    except ValueError:
        return None
    return candidate if candidate.is_file() else None


def classify_validation_target(
    milestone: dict[str, Any],
    *,
    workspace: Optional[Path] = None,
) -> tuple[str, str]:
    """Decide ``ui`` vs ``python`` for ``auto``-profile milestones.

    Structural signals only — file suffixes, Streamlit imports, and frontend
    manifests. Free-text prose (titles, descriptions, criteria) is NEVER
    consulted: that is what misclassified a training-loop hotfix as a UI
    task. Returns ``(profile, reason)`` for logging and tests.
    """
    ws = workspace or get_workspace_root()
    targets = [
        str(path).strip()
        for path in milestone.get("target_files", [])
        if str(path).strip()
    ]
    suffixes = {Path(path).suffix.lower() for path in targets}
    if suffixes & _UI_SUFFIXES:
        hit = sorted(suffixes & _UI_SUFFIXES)
        return "ui", f"UI file suffixes in targets: {hit}"

    for rel in targets:
        if not rel.lower().endswith(".py"):
            continue
        resolved = _resolve_target(rel, ws)
        if resolved is None:
            continue
        try:
            if resolved.stat().st_size > _MAX_PROBE_BYTES:
                continue
            text = resolved.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if _STREAMLIT_IMPORT_RE.search(text):
            return "ui", f"Streamlit import in {rel}"

    if (ws / "package.json").is_file() and suffixes & _JS_SUFFIXES:
        hit = sorted(suffixes & _JS_SUFFIXES)
        return "ui", f"JS targets in a package.json project: {hit}"

    return "python", "no structural UI signals (suffixes, Streamlit imports, manifests)"


def _criteria(milestone: dict[str, Any]) -> list[str]:
    values = milestone.get("acceptance_criteria", [])
    if not isinstance(values, list):
        return []
    return [str(value).strip() for value in values if str(value).strip()]


def _ui_text_checks(criteria: list[str]) -> list[dict[str, str]]:
    checks: list[dict[str, str]] = []
    seen: set[str] = set()
    for criterion in criteria:
        for match in _QUOTED_TEXT.findall(criterion):
            text = match.strip()
            if text.lower() in seen:
                continue
            seen.add(text.lower())
            checks.append({"action": "assert_text", "text": text})
    return checks


def _target_paths(milestone: dict[str, Any]) -> list[str]:
    return [
        normalize_workspace_path(str(path))
        for path in milestone.get("target_files", [])
        if str(path).strip()
    ]


def _available_port() -> int:
    for port in get_allowed_ports():
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
            try:
                probe.bind(("127.0.0.1", port))
            except OSError:
                continue
            return port
    return 0


def compile_validation_contract(
    milestone: dict[str, Any],
) -> tuple[dict[str, Any] | None, str | None]:
    """Return an internal contract or a human-readable compilation error."""
    targets = _target_paths(milestone)
    criteria = _criteria(milestone)
    if not targets:
        return None, "work packet has no target_files"
    if not criteria:
        return None, "work packet has no acceptance_criteria"

    profile = _profile(milestone)
    if not profile:
        return None, (
            "validation_profile must be one of: auto, ui, python, lint, structural"
        )
    if profile == "auto":
        classified, reason = classify_validation_target(milestone)
        profile = classified
        print(f"  [Validation] auto profile → {profile} ({reason})")

    if profile == "ui":
        workspace = get_workspace_root()
        html_targets = [path for path in targets if path.endswith(".html")]
        entry = html_targets[0] if html_targets else "index.html"
        port = _available_port()
        if not port:
            return None, "no available local port for UI validation"
        criteria_text = " ".join(criteria).lower()
        is_vite = (workspace / "package.json").exists() and not html_targets
        is_streamlit = "streamlit" in criteria_text
        if is_vite:
            server = {"kind": "vite", "port": port}
            command_argv: list[str] = []
        elif is_streamlit:
            server = {"kind": "streamlit", "port": port, "app_path": entry}
            command_argv = []
        else:
            command_argv = [
                "python", "-m", "http.server", str(port), "--bind", "127.0.0.1",
            ]
            server = {
                "kind": "generic",
                "port": port,
                "app_path": entry,
                "command": command_argv,
            }
        checks = _ui_text_checks(criteria)
        if not checks:
            checks.append({"action": "snapshot"})
        checks.extend([
            {"action": "accessibility"},
            {"action": "audit"},
            {"action": "screenshot"},
        ])
        return {
            "type": "ui_smoke",
            "language": "html",
            "command": shlex.join(command_argv),
            "serve": server,
            "checks": checks,
            "pass_criteria": "All acceptance criteria are visibly satisfied by the rendered UI.",
        }, None

    if profile == "lint":
        command_argv = ["python", "-m", "flake8", *targets, "--max-line-length=120"]
        return {
            "type": "lint",
            "language": "python",
            "command": shlex.join(command_argv),
            "pass_criteria": "The target files pass linting.",
        }, None

    if profile == "structural":
        return {
            "type": "structural",
            "language": "generic",
            "command": "",
            "pass_criteria": "\n".join(criteria),
        }, None

    test_targets = [
        path for path in targets
        if path.startswith("tests/") or Path(path).name.startswith("test_")
    ]
    pytest_target = test_targets or ["tests"]
    command_argv = ["python", "-m", "pytest", *pytest_target, "-q"]
    return {
        "type": "pytest",
        "language": "python",
        "command": shlex.join(command_argv),
        "pass_criteria": "\n".join(criteria),
    }, None
