"""Compile high-level work-packet intent into internal validation contracts.

The orchestrator owns goals and acceptance criteria. This module owns the
executable details consumed by the validator and worker auto-feedback loop.
Those details never need to be generated by the planning model.
"""

from __future__ import annotations

import re
import shlex
import socket
from pathlib import Path
from typing import Any

from src.tools.paths import get_workspace_root, normalize_workspace_path
from src.sandbox.process_manager import get_allowed_ports

_UI_HINTS = ("ui", "html", "frontend", "react", "vite", "streamlit", "browser", "web")
_QUOTED_TEXT = re.compile(r"""['"]([^'"]{2,120})['"]""")


def _profile(milestone: dict[str, Any]) -> str:
    value = str(milestone.get("validation_profile", "auto")).strip().lower()
    if value in {"auto", "ui", "python", "lint", "structural"}:
        return value
    return ""


def _is_ui_milestone(milestone: dict[str, Any]) -> bool:
    profile = _profile(milestone)
    if profile == "ui":
        return True
    if profile in {"python", "lint", "structural"}:
        return False
    text = " ".join(
        [
            str(milestone.get("title", "")),
            str(milestone.get("description", "")),
            " ".join(str(item) for item in milestone.get("acceptance_criteria", [])),
        ]
    ).lower()
    targets = [str(path).lower() for path in milestone.get("target_files", [])]
    return any(hint in text for hint in _UI_HINTS) or any(
        path.endswith((".html", ".jsx", ".tsx", ".vue")) for path in targets
    )


def _criteria(milestone: dict[str, Any]) -> list[str]:
    values = milestone.get("acceptance_criteria", [])
    if not isinstance(values, list):
        return []
    return [str(value).strip() for value in values if str(value).strip()]


def _ui_text_checks(criteria: list[str]) -> list[dict[str, str]]:
    checks: list[dict[str, str]] = []
    seen: set[str] = set()
    for criterion in criteria:
        for match in _QUOTED_TEXT.findall(criterion):
            text = match.strip()
            if text.lower() in seen:
                continue
            seen.add(text.lower())
            checks.append({"action": "assert_text", "text": text})
    return checks


def _target_paths(milestone: dict[str, Any]) -> list[str]:
    return [
        normalize_workspace_path(str(path))
        for path in milestone.get("target_files", [])
        if str(path).strip()
    ]


def _available_port() -> int:
    for port in get_allowed_ports():
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
            try:
                probe.bind(("127.0.0.1", port))
            except OSError:
                continue
            return port
    return 0


def compile_validation_contract(
    milestone: dict[str, Any],
) -> tuple[dict[str, Any] | None, str | None]:
    """Return an internal contract or a human-readable compilation error."""
    targets = _target_paths(milestone)
    criteria = _criteria(milestone)
    if not targets:
        return None, "work packet has no target_files"
    if not criteria:
        return None, "work packet has no acceptance_criteria"

    profile = _profile(milestone)
    if not profile:
        return None, (
            "validation_profile must be one of: auto, ui, python, lint, structural"
        )
    if profile == "auto":
        profile = "ui" if _is_ui_milestone(milestone) else "python"

    if profile == "ui":
        workspace = get_workspace_root()
        html_targets = [path for path in targets if path.endswith(".html")]
        entry = html_targets[0] if html_targets else "index.html"
        port = _available_port()
        if not port:
            return None, "no available local port for UI validation"
        criteria_text = " ".join(criteria).lower()
        is_vite = (workspace / "package.json").exists() and not html_targets
        is_streamlit = "streamlit" in criteria_text
        if is_vite:
            server = {"kind": "vite", "port": port}
            command_argv: list[str] = []
        elif is_streamlit:
            server = {"kind": "streamlit", "port": port, "app_path": entry}
            command_argv = []
        else:
            command_argv = [
                "python", "-m", "http.server", str(port), "--bind", "127.0.0.1",
            ]
            server = {
                "kind": "generic",
                "port": port,
                "app_path": entry,
                "command": command_argv,
            }
        checks = _ui_text_checks(criteria)
        if not checks:
            checks.append({"action": "snapshot"})
        checks.extend([
            {"action": "accessibility"},
            {"action": "audit"},
            {"action": "screenshot"},
        ])
        return {
            "type": "ui_smoke",
            "language": "html",
            "command": shlex.join(command_argv),
            "serve": server,
            "checks": checks,
            "pass_criteria": "All acceptance criteria are visibly satisfied by the rendered UI.",
        }, None

    if profile == "lint":
        command_argv = ["python", "-m", "flake8", *targets, "--max-line-length=120"]
        return {
            "type": "lint",
            "language": "python",
            "command": shlex.join(command_argv),
            "pass_criteria": "The target files pass linting.",
        }, None

    if profile == "structural":
        return {
            "type": "structural",
            "language": "generic",
            "command": "",
            "pass_criteria": "\n".join(criteria),
        }, None

    test_targets = [
        path for path in targets
        if path.startswith("tests/") or Path(path).name.startswith("test_")
    ]
    pytest_target = test_targets or ["tests"]
    command_argv = ["python", "-m", "pytest", *pytest_target, "-q"]
    return {
        "type": "pytest",
        "language": "python",
        "command": shlex.join(command_argv),
        "pass_criteria": "\n".join(criteria),
    }, None
